# Generated by Django 4.2.23 on 2025-07-24 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StudentModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25)),
                ('roll', models.IntegerField()),
                ('city', models.CharField(max_length=25)),
                ('passby', models.CharField(max_length=25)),
            ],
        ),
    ]
