# Generated by Django 4.2.23 on 2025-07-26 12:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_songmodel_song'),
    ]

    operations = [
        migrations.AlterField(
            model_name='songmodel',
            name='song',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sungby', to='api.singermodel'),
        ),
    ]
