from django.db import models
from django.db.models.signals import post_save
from django.dispatch import receiver
from rest_framework.authtoken.models import Token
from django.conf import settings
# Create your models here.
class StudentModel(models.Model):
    roll=models.IntegerField()
    name=models.CharField(max_length=25)
    email=models.EmailField()

    def __str__(self) -> str:
        return self.name
    
    # creating signals for user, when user creates automatically token generated by signal
    @receiver(post_save,sender=settings.AUTH_USER_MODEL)
    def create_auth_token(sender,instance=None,created=False,**kwargs):
        if created:
            Token.objects.create(user=instance)