# Generated by Django 4.2.23 on 2025-07-18 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentmodel',
            name='roll',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
